export const LIMIT_DEFAULT = 10
export const PAGE_CURRENT_DEFAULT = 1
export const ROWS_PER_PAGE_OPTIONS = [10, 20, 25, 50, 100]
export const CUSTOMER_STATUS = {
  DRAFT: 1,
  IN_CONTACT: 2,
  CONFIRM_COLLABORATION: 3,
  SIGN_CONTRACT: 4,
  CONTRACT_EXPIRED: 5,
  END_COLLABORATION: 6,
  OTHER: 7,
}
